name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies: 
  import_lint:
    path: ../

dev_dependencies:
  
  lints: ^2.0.0
  dart_code_metrics: ^5.6.0
